spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true

mail:
  address:
    admin: admin@gmail #${ADMIN_EMAIL}
jwt:
  key: aaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbb #${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1440 #${JWT_ACCESS_EXP_MIN}
  refresh-token-expiration-minutes: 1440 #${JWT_REFRESH_EXP_MIN}